export interface Character {
  id: number;
  echo: boolean;
  name: string;
  icon: string;
}

export const characters: Character[] = [
  { id: 1, echo: false, name: "Mario", icon: "stock-icons/mario.png" },
  {
    id: 2,
    echo: false,
    name: "Donkey Kong",
    icon: "stock-icons/donkey_kong.png",
  },
  { id: 3, echo: false, name: "Link", icon: "stock-icons/link.png" },
  { id: 4, echo: false, name: "Samus", icon: "stock-icons/samus.png" },
  { id: 4, echo: true, name: "Dark Samus", icon: "stock-icons/dark_samus.png" },
  { id: 5, echo: false, name: "Yoshi", icon: "stock-icons/yoshi.png" },
  { id: 6, echo: false, name: "Kirby", icon: "stock-icons/kirby.png" },
  { id: 7, echo: false, name: "Fox", icon: "stock-icons/fox.png" },
  { id: 8, echo: false, name: "Pikachu", icon: "stock-icons/pikachu.png" },
  { id: 9, echo: false, name: "Luigi", icon: "stock-icons/luigi.png" },
  { id: 10, echo: false, name: "Ness", icon: "stock-icons/ness.png" },
  {
    id: 11,
    echo: false,
    name: "Captain Falcon",
    icon: "stock-icons/captain_falcon.png",
  },
  {
    id: 12,
    echo: false,
    name: "Jigglypuff",
    icon: "stock-icons/jigglypuff.png",
  },
  { id: 13, echo: false, name: "Peach", icon: "stock-icons/peach.png" },
  { id: 13, echo: true, name: "Daisy", icon: "stock-icons/daisy.png" },
  { id: 14, echo: false, name: "Bowser", icon: "stock-icons/bowser.png" },
  {
    id: 15,
    echo: false,
    name: "Ice Climbers",
    icon: "stock-icons/ice_climbers.png",
  },
  { id: 16, echo: false, name: "Sheik", icon: "stock-icons/sheik.png" },
  { id: 17, echo: false, name: "Zelda", icon: "stock-icons/zelda.png" },
  { id: 18, echo: false, name: "Dr. Mario", icon: "stock-icons/dr_mario.png" },
  { id: 19, echo: false, name: "Pichu", icon: "stock-icons/pichu.png" },
  { id: 20, echo: false, name: "Falco", icon: "stock-icons/falco.png" },
  { id: 21, echo: false, name: "Marth", icon: "stock-icons/marth.png" },
  { id: 21, echo: true, name: "Lucina", icon: "stock-icons/lucina.png" },
  {
    id: 22,
    echo: false,
    name: "Young Link",
    icon: "stock-icons/young_link.png",
  },
  { id: 23, echo: false, name: "Ganondorf", icon: "stock-icons/ganondorf.png" },
  { id: 24, echo: false, name: "Mewtwo", icon: "stock-icons/mewtwo.png" },
  { id: 25, echo: false, name: "Roy", icon: "stock-icons/roy.png" },
  { id: 25, echo: true, name: "Chrom", icon: "stock-icons/chrom.png" },
  {
    id: 26,
    echo: false,
    name: "Mr. Game & Watch",
    icon: "stock-icons/mr_game_and_watch.png",
  },
  {
    id: 27,
    echo: false,
    name: "Meta Knight",
    icon: "stock-icons/meta_knight.png",
  },
  { id: 28, echo: false, name: "Pit", icon: "stock-icons/pit.png" },
  { id: 28, echo: true, name: "Dark Pit", icon: "stock-icons/dark_pit.png" },
  {
    id: 29,
    echo: false,
    name: "Zero Suit Samus",
    icon: "stock-icons/zero_suit_samus.png",
  },
  { id: 30, echo: false, name: "Wario", icon: "stock-icons/wario.png" },
  { id: 31, echo: false, name: "Snake", icon: "stock-icons/snake.png" },
  { id: 32, echo: false, name: "Ike", icon: "stock-icons/ike.png" },

  {
    id: 33,
    echo: false,
    name: "Pokemon Trainer",
    icon: "stock-icons/pokemon_trainer.png",
  },

  {
    id: 36,
    echo: false,
    name: "Diddy Kong",
    icon: "stock-icons/diddy_kong.png",
  },
  { id: 37, echo: false, name: "Lucas", icon: "stock-icons/lucas.png" },
  { id: 38, echo: false, name: "Sonic", icon: "stock-icons/sonic.png" },
  {
    id: 39,
    echo: false,
    name: "King Dedede",
    icon: "stock-icons/king_dedede.png",
  },
  { id: 40, echo: false, name: "Olimar", icon: "stock-icons/olimar.png" },
  { id: 41, echo: false, name: "Lucario", icon: "stock-icons/lucario.png" },
  { id: 42, echo: false, name: "R.O.B.", icon: "stock-icons/rob.png" },
  { id: 43, echo: false, name: "Toon Link", icon: "stock-icons/toon_link.png" },
  { id: 44, echo: false, name: "Wolf", icon: "stock-icons/wolf.png" },
  { id: 45, echo: false, name: "Villager", icon: "stock-icons/villager.png" },
  { id: 46, echo: false, name: "Mega Man", icon: "stock-icons/mega_man.png" },
  {
    id: 47,
    echo: false,
    name: "Wii Fit Trainer",
    icon: "stock-icons/wii_fit_trainer.png",
  },
  {
    id: 48,
    echo: false,
    name: "Rosalina & Luma",
    icon: "stock-icons/rosalina_and_luma.png",
  },
  {
    id: 49,
    echo: false,
    name: "Little Mac",
    icon: "stock-icons/little_mac.png",
  },
  { id: 50, echo: false, name: "Greninja", icon: "stock-icons/greninja.png" },
  {
    id: 51,
    echo: false,
    name: "Mii Brawler",
    icon: "stock-icons/mii_brawler.png",
  },
  {
    id: 52,
    echo: false,
    name: "Mii Swordfighter",
    icon: "stock-icons/mii_swordfighter.png",
  },
  {
    id: 53,
    echo: false,
    name: "Mii Gunner",
    icon: "stock-icons/mii_gunner.png",
  },
  { id: 54, echo: false, name: "Palutena", icon: "stock-icons/palutena.png" },
  { id: 55, echo: false, name: "Pac-Man", icon: "stock-icons/pac_man.png" },
  { id: 56, echo: false, name: "Robin", icon: "stock-icons/robin.png" },
  { id: 57, echo: false, name: "Shulk", icon: "stock-icons/shulk.png" },
  {
    id: 58,
    echo: false,
    name: "Bowser Jr.",
    icon: "stock-icons/bowser_jr.png",
  },
  { id: 59, echo: false, name: "Duck Hunt", icon: "stock-icons/duck_hunt.png" },
  { id: 60, echo: false, name: "Ryu", icon: "stock-icons/ryu.png" },
  { id: 60, echo: true, name: "Ken", icon: "stock-icons/ken.png" },
  { id: 61, echo: false, name: "Cloud", icon: "stock-icons/cloud.png" },
  { id: 62, echo: false, name: "Corrin", icon: "stock-icons/corrin.png" },
  { id: 63, echo: false, name: "Bayonetta", icon: "stock-icons/bayonetta.png" },
  { id: 64, echo: false, name: "Inkling", icon: "stock-icons/inkling.png" },
  { id: 65, echo: false, name: "Ridley", icon: "stock-icons/ridley.png" },
  { id: 66, echo: false, name: "Simon", icon: "stock-icons/simon.png" },
  { id: 66, echo: true, name: "Richter", icon: "stock-icons/richter.png" },
  {
    id: 67,
    echo: false,
    name: "King K. Rool",
    icon: "stock-icons/king_k_rool.png",
  },
  { id: 68, echo: false, name: "Isabelle", icon: "stock-icons/isabelle.png" },
  {
    id: 69,
    echo: false,
    name: "Incineroar",
    icon: "stock-icons/gaogaen.png",
  },
  {
    id: 70,
    echo: false,
    name: "Piranha Plant",
    icon: "stock-icons/packun_flower.png",
  },
  { id: 71, echo: false, name: "Joker", icon: "stock-icons/joker.png" },
  { id: 72, echo: false, name: "Hero", icon: "stock-icons/dq_hero.png" },
  {
    id: 73,
    echo: false,
    name: "Banjo & Kazooie",
    icon: "stock-icons/banjo_and_kazooie.png",
  },
  { id: 74, echo: false, name: "Terry", icon: "stock-icons/terry.png" },
  { id: 75, echo: false, name: "Byleth", icon: "stock-icons/byleth.png" },
  { id: 76, echo: false, name: "Min Min", icon: "stock-icons/minmin.png" },
  { id: 77, echo: false, name: "Steve", icon: "stock-icons/steve.png" },
  { id: 78, echo: false, name: "Sephiroth", icon: "stock-icons/sephiroth.png" },
  { id: 79, echo: false, name: "Pyra/Mythra", icon: "stock-icons/homura.png" },
  { id: 81, echo: false, name: "Kazuya", icon: "stock-icons/kazuya.png" },
  { id: 82, echo: false, name: "Sora", icon: "stock-icons/sora.png" },
];

export function getCharacterByName(name: string): Character | undefined {
  return characters.find((c) => c.name.toLowerCase() === name.toLowerCase());
}
